### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by FlicAnderson** [code-review-cupid/code-review-cupid-admin#5]

**Comment by FlicAnderson** [comment]
@jsteyn and @shermanlo77 can you describe how you've put the website together, and any design decisions, so we have a record here for future collaborators? Thanks!

**Comment by shermanlo77** [comment]
A webpage template from [w3school](https://www.w3schools.com/w3css/w3css_templates.asp) was used. Fields on webpage should match those of backend, still implementing...

**Comment by FlicAnderson** [comment]
#13 has been created and put in place by @shermanlo77, as has #14. 

Current setup is: 
Landing/home page with links to create profile form. 
Example profile content as 'find your match' link (no selection). 
'Next steps' tab links to our README #9 in the project admin github repo, as does our 'contribute' link.

**Comment by jsteyn** [comment]
Done and dusted
